#!/bin/bash

set -e

dehumanise() {
  echo "$1" | awk \
    'BEGIN{IGNORECASE = 1}
     function printpower(n,b,p) {printf "%u\n", n*b^p; next}
     /[0-9]$/{print $1;next};
     /K(iB)?$/{printpower($1,  2, 10)};
     /M(iB)?$/{printpower($1,  2, 20)};
     /G(iB)?$/{printpower($1,  2, 30)};
     /T(iB)?$/{printpower($1,  2, 40)};
     /KB$/{    printpower($1, 10,  3)};
     /MB$/{    printpower($1, 10,  6)};
     /GB$/{    printpower($1, 10,  9)};
     /TB$/{    printpower($1, 10, 12)}'
}

create_cgroup() {
  local bytes
  bytes=$(dehumanise "$3")
  mkdir -p "/sys/fs/cgroup/memory/$1/$2"
  echo "$bytes" > "/sys/fs/cgroup/memory/$1/$2/memory.limit_in_bytes"
  echo "$bytes" > "/sys/fs/cgroup/memory/$1/$2/memory.memsw.limit_in_bytes"
  chown "$1:$1" "/sys/fs/cgroup/memory/$1/$2/tasks"
}

awk -F: '/\/home/ && ($3 >= 1000) {printf "%s\n", $1}' /etc/passwd | while read -r user
do
  create_cgroup "$user" archiver 4G
  create_cgroup "$user" browser 6G
  create_cgroup "$user" media 2G
  create_cgroup "$user" messenger 2G
  create_cgroup "$user" torrent 1G
  create_cgroup "$user" wine 6G
  create_cgroup "$user" other 2G
done
