#!/bin/sh

mkdir -p ~/.bin-fj

APPS=$(find ~/.config/firejail -maxdepth 1 \( -type l -o -type f \) -printf "%f\n" | grep -E '\.profile$' | rev | cut -c 9- | rev | sort -u)

for APP in $APPS; do
    if [ -e "/bin/$APP" ]; then
        ln -sr ~/.bin/fj-run ~/.bin-fj/"$APP"
    fi
done
