#!/bin/sh

if [ "$1" != '' ]
then
    if [ -f ~/.ssh/known_hosts ]
    then
        egrep "$1[^ ]* [^ ]*" ~/.ssh/known_hosts
        egrep -v "$1[^ ]* [^ ]*" ~/.ssh/known_hosts > ~/.ssh/known_hosts_cleared
        mv ~/.ssh/known_hosts_cleared ~/.ssh/known_hosts
    fi
else
    echo "Usage: ssh-delete-host PATTERN"
fi
