#!/bin/bash

set -e

echo $$ > "/sys/fs/cgroup/memory/$USER/media/tasks"

exec bwrap \
     --ro-bind /usr/bin/deadbeef /usr/bin/deadbeef \
     \
     --ro-bind /usr/share /usr/share \
     \
     --ro-bind /usr/lib /usr/lib \
     --tmpfs /usr/lib/modules \
     --tmpfs /usr/lib/systemd \
     --tmpfs /usr/lib/gcc \
     \
     --symlink /usr/lib /usr/lib64 \
     --symlink /usr/lib /lib64 \
     --symlink /usr/lib /lib \
     --symlink /usr/bin /bin \
     --symlink /usr/bin /sbin \
     \
     --proc /proc \
     \
     --dev /dev \
     \
     --ro-bind /var/lib/dbus/machine-id /var/lib/dbus/machine-id \
     \
     --ro-bind /tmp/.X11-unix /tmp/.X11-unix \
     \
     --ro-bind /etc/gtk-2.0 /etc/gtk-2.0 \
     --ro-bind /etc/gtk-3.0 /etc/gtk-3.0 \
     --ro-bind /etc/fonts /etc/fonts \
     --ro-bind /etc/pulse /etc/pulse \
     \
     --tmpfs /run \
     `# Necessary for MPRIS2` \
     --bind "/run/user/$UID/bus" "/run/user/$UID/bus" \
     --bind "/run/user/$UID/pulse" "/run/user/$UID/pulse" \
     \
     --ro-bind ~ ~ \
     --tmpfs ~/.gnupg \
     --tmpfs ~/.ssh \
     --bind ~/.config/pulse ~/.config/pulse \
     --bind ~/.config/deadbeef ~/.config/deadbeef \
     --bind ~/.cache/deadbeef ~/.cache/deadbeef \
     \
     --unsetenv MAIL \
     --unsetenv SHELL \
     \
     --unshare-user \
     --unshare-ipc \
     --unshare-pid \
     --unshare-net \
     --unshare-uts \
     --unshare-cgroup \
     \
     --new-session \
     --die-with-parent \
     \
     --cap-drop ALL \
     \
     --seccomp 3 \
     3< ~/.seccomp/seccomp.bpf \
     \
     /usr/bin/deadbeef "$@"
