#!/bin/bash

set -e

echo $$ > "/sys/fs/cgroup/memory/$USER/1G/tasks"

mapfile -t video < <(find /dev -maxdepth 1 -type c -regex '/dev/video[0-9]+' | sed 's/.*/--dev-bind\n&\n&/')

exec bwrap \
     --ro-bind /usr/bin/ffmpeg /usr/bin/ffmpeg \
     \
     --ro-bind /usr/share /usr/share \
     \
     --ro-bind /usr/lib /usr/lib \
     --tmpfs /usr/lib/modules \
     --tmpfs /usr/lib/systemd \
     --tmpfs /usr/lib/gcc \
     \
     --symlink /usr/lib /usr/lib64 \
     --symlink /usr/lib /lib64 \
     --symlink /usr/lib /lib \
     --symlink /usr/bin /bin \
     --symlink /usr/bin /sbin \
     \
     --proc /proc \
     \
     --ro-bind /opt/intel/mediasdk /opt/intel/mediasdk \
     \
     --dev /dev \
     --dev-bind /dev/dri /dev/dri \
     `# Necessary for camera access` \
     "${video[@]}" \
     \
     `# Necessary for hardware acceleration` \
     --ro-bind /sys/dev /sys/dev \
     --ro-bind /sys/devices /sys/devices \
     \
     --ro-bind /etc/ld.so.cache /etc/ld.so.cache \
     --ro-bind /etc/ld.so.conf /etc/ld.so.conf \
     --ro-bind /etc/ld.so.conf.d /etc/ld.so.conf.d \
     \
     --tmpfs /run \
     \
     --bind ~ ~ \
     --tmpfs ~/.gnupg \
     --tmpfs ~/.ssh \
     \
     --unsetenv DBUS_SESSION_BUS_ADDRESS \
     --unsetenv XDG_RUNTIME_DIR \
     --unsetenv XAUTHORITY \
     --unsetenv MAIL \
     --unsetenv SHELL \
     \
     --unshare-user \
     --unshare-ipc \
     --unshare-pid \
     --unshare-net \
     --unshare-uts \
     --unshare-cgroup \
     \
     --new-session \
     --die-with-parent \
     \
     --cap-drop ALL \
     \
     --seccomp 3 \
     3< ~/.seccomp/seccomp.bpf \
     \
     /usr/bin/ffmpeg "$@"
