#!/usr/bin/env bash

set -euETo pipefail
shopt -s inherit_errexit

mapfile -t video < <(find /dev -maxdepth 1 -type c -regex '/dev/video[0-9]+' | sed 's/.*/--dev-bind\n&\n&/')

exec bwrap \
     --ro-bind /usr/bin/firefox /usr/bin/firefox \
     `# Necessary for passff` \
     --ro-bind /usr/bin/env /usr/bin/env \
     --ro-bind /usr/bin/sh /usr/bin/sh \
     --ro-bind /usr/bin/bash /usr/bin/bash \
     --ro-bind /usr/bin/python3 /usr/bin/python3 \
     --ro-bind /usr/bin/python3.9 /usr/bin/python3.9 \
     --ro-bind /usr/bin/getopt /usr/bin/getopt \
     --ro-bind /usr/bin/tail /usr/bin/tail \
     --ro-bind /usr/bin/tree /usr/bin/tree \
     --ro-bind /usr/bin/sed /usr/bin/sed \
     --ro-bind /usr/bin/gpg /usr/bin/gpg \
     --ro-bind /usr/bin/gpg2 /usr/bin/gpg2 \
     --ro-bind /usr/bin/base64 /usr/bin/base64 \
     --ro-bind /usr/bin/which /usr/bin/which \
     --ro-bind /usr/bin/oathtool /usr/bin/oathtool \
     --ro-bind /usr/bin/pass /usr/bin/pass \
     \
     --ro-bind /usr/share /usr/share \
     \
     --ro-bind /usr/lib /usr/lib \
     --tmpfs /usr/lib/modules \
     --tmpfs /usr/lib/systemd \
     --tmpfs /usr/lib/gcc \
     \
     --symlink /usr/lib /usr/lib64 \
     --symlink /usr/lib /lib64 \
     --symlink /usr/lib /lib \
     --symlink /usr/bin /bin \
     --symlink /usr/bin /sbin \
     \
     --proc /proc \
     \
     --dev /dev \
     --dev-bind /dev/dri /dev/dri \
     `# Necessary for camera access` \
     "${video[@]}" \
     \
     `# Necessary for hardware acceleration` \
     --ro-bind /sys/dev /sys/dev \
     --ro-bind /sys/devices /sys/devices \
     \
     --ro-bind /var/lib/dbus/machine-id /var/lib/dbus/machine-id \
     \
     --ro-bind /tmp/.X11-unix /tmp/.X11-unix \
     \
     --ro-bind /etc/fonts /etc/fonts \
     --ro-bind /etc/pulse /etc/pulse \
     --ro-bind /etc/gtk-2.0 /etc/gtk-2.0 \
     --ro-bind /etc/gtk-3.0 /etc/gtk-3.0 \
     --ro-bind /etc/resolv.conf /etc/resolv.conf \
     --ro-bind /etc/localtime /etc/localtime \
     \
     --tmpfs /run \
     --bind "/run/user/$UID/bus" "/run/user/$UID/bus" \
     --bind "/run/user/$UID/gnupg" "/run/user/$UID/gnupg" \
     --bind "/run/user/$UID/pulse" "/run/user/$UID/pulse" \
     \
     --bind ~/.mozilla ~/.mozilla \
     --bind ~/.cache/mozilla/firefox ~/.cache/mozilla/firefox \
     --bind ~/Downloads ~/Downloads \
     --ro-bind ~/.password-store ~/.password-store \
     --bind ~/.gnupg ~/.gnupg \
     --ro-bind ~/.config/gtk-3.0 ~/.config/gtk-3.0 \
     --bind ~/.config/pulse ~/.config/pulse \
     --ro-bind ~/.Xauthority ~/.Xauthority \
     \
     --unsetenv MAIL \
     --setenv SHELL /bin/bash \
     \
     --unshare-user \
     --unshare-ipc \
     --unshare-pid \
     --unshare-uts \
     --unshare-cgroup \
     \
     --new-session \
     --die-with-parent \
     \
     --cap-drop ALL \
     \
     --seccomp 3 \
     3< ~/.seccomp/seccomp.bpf \
     \
     /usr/bin/firefox "$@"
