#!/usr/bin/env bash

set -euETo pipefail
shopt -s inherit_errexit

exec bwrap \
     --ro-bind /usr/bin/imv /usr/bin/imv \
     --ro-bind /usr/bin/imv-x11 /usr/bin/imv-x11 \
     --ro-bind /usr/bin/imv-wayland /usr/bin/imv-wayland \
     --ro-bind /usr/bin/sh /usr/bin/sh \
     --ro-bind /usr/bin/bash /usr/bin/bash \
     \
     --ro-bind /usr/share /usr/share \
     \
     --ro-bind /usr/lib /usr/lib \
     --tmpfs /usr/lib/modules \
     --tmpfs /usr/lib/systemd \
     --tmpfs /usr/lib/gcc \
     \
     --symlink /usr/lib /usr/lib64 \
     --symlink /usr/lib /lib64 \
     --symlink /usr/lib /lib \
     --symlink /usr/bin /bin \
     --symlink /usr/bin /sbin \
     \
     --proc /proc \
     \
     --dev /dev \
     \
     --ro-bind /tmp/.X11-unix /tmp/.X11-unix \
     \
     --ro-bind /etc/fonts /etc/fonts \
     \
     --tmpfs /run \
     \
     --ro-bind ~ ~ \
     --tmpfs ~/.gnupg \
     --tmpfs ~/.ssh \
     \
     --unsetenv DBUS_SESSION_BUS_ADDRESS \
     --unsetenv XDG_RUNTIME_DIR \
     --unsetenv MAIL \
     --setenv SHELL /bin/bash \
     \
     --unshare-user \
     --unshare-ipc \
     --unshare-pid \
     --unshare-net \
     --unshare-uts \
     --unshare-cgroup \
     \
     --new-session \
     --die-with-parent \
     \
     --cap-drop ALL \
     \
     --seccomp 3 \
     3< ~/.seccomp/seccomp.bpf \
     \
     /usr/bin/imv "$@"
