#!/usr/bin/env bash

set -euETo pipefail
shopt -s inherit_errexit

exec bwrap \
     --ro-bind /usr/bin /usr/bin \
     \
     --ro-bind /usr/share /usr/share \
     \
     --ro-bind /usr/lib /usr/lib \
     --tmpfs /usr/lib/modules \
     --tmpfs /usr/lib/systemd \
     --tmpfs /usr/lib/gcc \
     \
     --symlink /usr/lib /usr/lib64 \
     --symlink /usr/lib /lib64 \
     --symlink /usr/lib /lib \
     --symlink /usr/bin /bin \
     --symlink /usr/bin /sbin \
     \
     --proc /proc \
     \
     --dev /dev \
     --dev-bind /dev/dri /dev/dri \
     \
     `# Necessary for hardware acceleration` \
     --ro-bind /sys/dev /sys/dev \
     --ro-bind /sys/devices /sys/devices \
     \
     `# xdg-screensaver creates a lockfile in /tmp` \
     --bind /tmp /tmp \
     \
     --ro-bind /etc/fonts /etc/fonts \
     --ro-bind /etc/pulse /etc/pulse \
     --ro-bind /etc/mpv /etc/mpv \
     \
     --tmpfs /run \
     --bind "/run/user/$UID/pulse" "/run/user/$UID/pulse" \
     \
     --ro-bind ~ ~ \
     --tmpfs ~/.gnupg \
     --tmpfs ~/.ssh \
     --bind ~/.cache/fontconfig ~/.cache/fontconfig \
     --bind ~/.config/pulse ~/.config/pulse \
     \
     --unsetenv DBUS_SESSION_BUS_ADDRESS \
     --unsetenv MAIL \
     --setenv SHELL /bin/bash \
     \
     `# unshare-pid breaks xdg-screensaver in a way that it can't detect` \
     `# process termination and therefore might not enable screensaver` \
     --unshare-user \
     --unshare-ipc \
     --unshare-net \
     --unshare-uts \
     --unshare-cgroup \
     \
     --new-session \
     --die-with-parent \
     \
     --cap-drop ALL \
     \
     --seccomp 3 \
     3< ~/.seccomp/seccomp.bpf \
     \
     /usr/bin/mpv "$@"
