#!/bin/bash

set -e

echo $$ > "/sys/fs/cgroup/memory/$USER/1G/tasks"

exec bwrap \
     --ro-bind /usr/bin/qbittorrent /usr/bin/qbittorrent \
     \
     --ro-bind /usr/share /usr/share \
     \
     --ro-bind /usr/lib /usr/lib \
     --tmpfs /usr/lib/modules \
     --tmpfs /usr/lib/systemd \
     --tmpfs /usr/lib/gcc \
     \
     --symlink /usr/lib /usr/lib64 \
     --symlink /usr/lib /lib64 \
     --symlink /usr/lib /lib \
     --symlink /usr/bin /bin \
     --symlink /usr/bin /sbin \
     \
     --proc /proc \
     \
     --dev /dev \
     --dev-bind /dev/dri /dev/dri \
     \
     `# Necessary for hardware acceleration` \
     --ro-bind /sys/dev /sys/dev \
     --ro-bind /sys/devices /sys/devices \
     \
     --ro-bind /var/lib/dbus/machine-id /var/lib/dbus/machine-id \
     \
     --ro-bind /tmp/.X11-unix /tmp/.X11-unix \
     \
     --ro-bind /etc/fonts /etc/fonts \
     --ro-bind /etc/resolv.conf /etc/resolv.conf \
     --ro-bind /etc/localtime /etc/localtime \
     \
     --tmpfs /run \
     --bind "/run/user/$UID/bus" "/run/user/$UID/bus" \
     \
     --bind ~/.local/share/data/qBittorrent ~/.local/share/data/qBittorrent \
     --bind ~/.config/qBittorrent ~/.config/qBittorrent \
     --bind ~/Torrents ~/Torrents \
     --bind ~/.Xauthority ~/.Xauthority \
     \
     --unsetenv MAIL \
     --unsetenv SHELL \
     \
     --unshare-user \
     --unshare-ipc \
     --unshare-pid \
     --unshare-uts \
     \
     --new-session \
     --die-with-parent \
     \
     --cap-drop ALL \
     \
     --seccomp 3 \
     3< ~/.seccomp/seccomp.bpf \
     \
     /usr/bin/qbittorrent "$@"
