#!/bin/bash

set -e

echo $$ > "/sys/fs/cgroup/memory/$USER/4G/tasks"

exec bwrap \
     --ro-bind /usr/share /usr/share \
     \
     --ro-bind /usr/lib /usr/lib \
     --tmpfs /usr/lib/modules \
     --tmpfs /usr/lib/systemd \
     --tmpfs /usr/lib/gcc \
     \
     --symlink /usr/lib /usr/lib64 \
     --symlink /usr/lib /lib64 \
     --symlink /usr/lib /lib \
     --symlink /usr/bin /bin \
     --symlink /usr/bin /sbin \
     \
     --proc /proc \
     \
     --dev /dev \
     \
     --ro-bind /opt/tor-browser-en /opt/tor-browser-en \
     \
     --ro-bind /tmp/.X11-unix /tmp/.X11-unix \
     \
     --tmpfs /run \
     \
     --bind ~/.tor-browser-en ~/.tor-browser-en \
     --ro-bind ~/.Xauthority ~/.Xauthority \
     \
     --unsetenv MAIL \
     --unsetenv SHELL \
     --setenv HOME ~/.tor-browser-en/INSTALL/Browser \
     --setenv FONTCONFIG_PATH ~/.tor-browser-en/INSTALL/Browser/TorBrowser/Data/fontconfig \
     --setenv FONTCONFIG_FILE fonts.conf \
     \
     --unshare-user \
     --unshare-ipc \
     --unshare-pid \
     --unshare-uts \
     --unshare-cgroup \
     \
     --new-session \
     --die-with-parent \
     \
     --cap-drop ALL \
     \
     --seccomp 3 \
     3< ~/.seccomp/seccomp.bpf \
     \
     ~/.tor-browser-en/INSTALL/Browser/firefox.real \
     --class "Tor Browser" \
     --profile ~/.tor-browser-en/INSTALL/Browser/TorBrowser/Data/Browser/profile.default \
     "$@"
