#!/bin/bash

set -e

exec bwrap \
     --ro-bind /usr/share /usr/share \
     \
     --ro-bind /usr/lib /usr/lib \
     --tmpfs /usr/lib/modules \
     --tmpfs /usr/lib/systemd \
     --tmpfs /usr/lib/gcc \
     \
     --symlink /usr/lib /usr/lib64 \
     --symlink /usr/lib /lib64 \
     --symlink /usr/lib /lib \
     \
     --proc /proc \
     \
     --dev /dev \
     \
     --ro-bind /opt/tor-browser /opt/tor-browser \
     \
     --ro-bind /tmp/.X11-unix /tmp/.X11-unix \
     \
     --tmpfs /run \
     \
     --bind ~/.tor-browser ~/.tor-browser \
     --ro-bind ~/.Xauthority ~/.Xauthority \
     \
     --unsetenv MAIL \
     --unsetenv SHELL \
     --setenv LD_LIBRARY_PATH ~/.tor-browser/app/Browser/TorBrowser/Tor \
     --setenv HOME ~/.tor-browser/app/Browser \
     --setenv FONTCONFIG_PATH ~/.tor-browser/app/Browser/TorBrowser/Data/fontconfig \
     --setenv FONTCONFIG_FILE fonts.conf \
     \
     --unshare-user \
     --unshare-ipc \
     --unshare-pid \
     --unshare-uts \
     --unshare-cgroup \
     \
     --new-session \
     --die-with-parent \
     \
     --cap-drop ALL \
     \
     --seccomp 3 \
     3< ~/.seccomp/seccomp.bpf \
     \
     ~/.tor-browser/app/Browser/firefox.real \
     --class "Tor Browser" \
     --profile ~/.tor-browser/app/Browser/TorBrowser/Data/Browser/profile.default \
     "$@"
