#!/bin/bash

set -e

echo $$ > "/sys/fs/cgroup/memory/$USER/messenger/tasks"

mapfile -t video < <(find /dev -maxdepth 1 -type c -regex '/dev/video[0-9]+' | sed 's/.*/--dev-bind\n&\n&/')

exec bwrap \
     --ro-bind /usr/bin/toxic /usr/bin/toxic \
     \
     --ro-bind /usr/share /usr/share \
     \
     --ro-bind /usr/lib /usr/lib \
     --tmpfs /usr/lib/modules \
     --tmpfs /usr/lib/systemd \
     --tmpfs /usr/lib/gcc \
     \
     --symlink /usr/lib /usr/lib64 \
     --symlink /usr/lib /lib64 \
     --symlink /usr/lib /lib \
     --symlink /usr/bin /bin \
     --symlink /usr/bin /sbin \
     \
     --proc /proc \
     \
     --dev /dev \
     --dev-bind /dev/dri /dev/dri \
     `# Necessary for camera access` \
     "${video[@]}" \
     \
     --ro-bind /tmp/.X11-unix /tmp/.X11-unix \
     \
     --ro-bind /etc/pulse /etc/pulse \
     --ro-bind /etc/localtime /etc/localtime \
     --ro-bind /etc/resolv.conf /etc/resolv.conf \
     \
     --tmpfs /run \
     --bind "/run/user/$UID/pulse" "/run/user/$UID/pulse" \
     \
     --bind ~/.config/tox ~/.config/tox \
     --bind ~/.config/pulse ~/.config/pulse \
     --ro-bind ~/.Xauthority ~/.Xauthority \
     \
     --unsetenv DBUS_SESSION_BUS_ADDRESS \
     --unsetenv MAIL \
     --unsetenv SHELL \
     \
     --unshare-user \
     --unshare-ipc \
     --unshare-pid \
     --unshare-uts \
     --unshare-cgroup \
     \
     --new-session \
     --die-with-parent \
     \
     --cap-drop ALL \
     \
     --seccomp 3 \
     3< ~/.seccomp/seccomp.bpf \
     \
     /usr/bin/toxic "$@"
