#!/bin/bash

set -e

exec bwrap \
     --ro-bind /usr/bin/vlc /usr/bin/vlc \
     `# VLC uses xdg-screensaver script to disable screensaver` \
     --ro-bind /usr/bin/xdg-screensaver /usr/bin/xdg-screensaver \
     --ro-bind /usr/bin/sh /usr/bin/sh \
     --ro-bind /usr/bin/bash /usr/bin/bash \
     --ro-bind /usr/bin/sed /usr/bin/sed \
     --ro-bind /usr/bin/hostname /usr/bin/hostname \
     --ro-bind /usr/bin/echo /usr/bin/echo \
     --ro-bind /usr/bin/grep /usr/bin/grep \
     --ro-bind /usr/bin/xset /usr/bin/xset \
     --ro-bind /usr/bin/xscreensaver-command /usr/bin/xscreensaver-command \
     \
     --ro-bind /usr/share /usr/share \
     \
     --ro-bind /usr/lib /usr/lib \
     --tmpfs /usr/lib/modules \
     --tmpfs /usr/lib/systemd \
     --tmpfs /usr/lib/gcc \
     \
     --symlink /usr/lib /usr/lib64 \
     --symlink /usr/lib /lib64 \
     --symlink /usr/lib /lib \
     --symlink /usr/bin /bin \
     --symlink /usr/bin /sbin \
     \
     --proc /proc \
     \
     --dev /dev \
     --dev-bind /dev/dri /dev/dri \
     \
     `# Necessary for hardware acceleration` \
     --ro-bind /sys/dev /sys/dev \
     --ro-bind /sys/devices /sys/devices \
     \
     --ro-bind /var/lib/dbus/machine-id /var/lib/dbus/machine-id \
     \
     --ro-bind /tmp/.X11-unix /tmp/.X11-unix \
     \
     --ro-bind /etc/fonts /etc/fonts \
     --ro-bind /etc/pulse /etc/pulse \
     \
     --tmpfs /run \
     --bind "/run/user/$UID/bus" "/run/user/$UID/bus" \
     --bind "/run/user/$UID/pulse" "/run/user/$UID/pulse" \
     \
     --ro-bind ~ ~ \
     --bind ~/.local/share/vlc ~/.local/share/vlc \
     --tmpfs ~/.gnupg \
     --tmpfs ~/.ssh \
     --bind ~/.config/pulse ~/.config/pulse \
     \
     --unsetenv DBUS_SESSION_BUS_ADDRESS \
     --unsetenv MAIL \
     --setenv SHELL /bin/bash \
     \
     --unshare-user \
     --unshare-ipc \
     --unshare-pid \
     --unshare-net \
     --unshare-uts \
     --unshare-cgroup \
     \
     --new-session \
     --die-with-parent \
     \
     --cap-drop ALL \
     \
     --seccomp 3 \
     3< ~/.seccomp/seccomp.bpf \
     \
     /usr/bin/vlc "$@"
