#!/usr/bin/env bash

set -euETo pipefail
shopt -s inherit_errexit

WINEPREFIX=${WINEPREFIX:-~/.wine}

exec bwrap \
     --ro-bind /usr/bin /usr/bin \
     \
     --ro-bind /usr/share /usr/share \
     \
     --ro-bind /usr/lib /usr/lib \
     --tmpfs /usr/lib/modules \
     --tmpfs /usr/lib/systemd \
     --tmpfs /usr/lib/gcc \
     \
     --ro-bind /usr/lib32 /usr/lib32 \
     \
     --symlink /usr/lib /usr/lib64 \
     --symlink /usr/lib /lib64 \
     --symlink /usr/lib /lib \
     --symlink /usr/bin /bin \
     --symlink /usr/bin /sbin \
     \
     --proc /proc \
     \
     --dev /dev \
     --dev-bind /dev/dri /dev/dri \
     \
     `# Necessary for hardware acceleration` \
     --ro-bind /sys/dev /sys/dev \
     --ro-bind /sys/devices /sys/devices \
     \
     --ro-bind /var/lib/dbus/machine-id /var/lib/dbus/machine-id \
     \
     --ro-bind /tmp/.X11-unix /tmp/.X11-unix \
     \
     --ro-bind /etc/fonts /etc/fonts \
     --ro-bind /etc/pulse /etc/pulse \
     --ro-bind /etc/gtk-2.0 /etc/gtk-2.0 \
     --ro-bind /etc/gtk-3.0 /etc/gtk-3.0 \
     --ro-bind /etc/resolv.conf /etc/resolv.conf \
     --ro-bind /etc/localtime /etc/localtime \
     \
     --tmpfs /run \
     --bind "/run/user/$UID/bus" "/run/user/$UID/bus" \
     --bind "/run/user/$UID/pulse" "/run/user/$UID/pulse" \
     \
     --bind "$WINEPREFIX" "$WINEPREFIX" \
     --ro-bind ~/.cache/wine ~/.cache/wine \
     --ro-bind ~/.cache/winetricks ~/.cache/winetricks \
     --bind ~/.config/pulse ~/.config/pulse \
     --ro-bind ~/.Xauthority ~/.Xauthority \
     \
     --unsetenv MAIL \
     --setenv SHELL /bin/bash \
     \
     --unshare-user \
     --unshare-ipc \
     --unshare-pid \
     --unshare-uts \
     \
     --new-session \
     --die-with-parent \
     \
     --cap-drop ALL \
     \
     /usr/bin/wine "$@"
